baseURL = "https://awicks.io"
title = "Alex Wicks"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Alex Wicks"
description = "Homepage of Alex Wicks"
keywords = "blog,developer,personal"
info = "DevOps · Linux · Automation"

avatarURL = "images/12629429.png"

dateFormat = "2006-01-02"

hideFooter = true
hideCredits = true
hideCopyright = true
since = 2019

rtl = false

colorScheme = "dark"
hideColorSchemeToggle = false

# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/aw1cks/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab"
weight = 2
url = "https://gitlab.com/aw1cks/"

[[params.social]]
name = "Email"
icon = "fa fa-envelope"
weight = 3
url = "mailto:alex@awicks.io"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Curriculum Vitae"
weight = 2
url = "https://cv.awicks.io"
